FROM node:18-alpine as build

WORKDIR /app
COPY frontend-web/package*.json ./
RUN npm ci
COPY frontend-web/ .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
